server:
  port: 8105
logging:
 level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/raze
    username: postgres
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#spring:
#  datasource:
#    password: M!r#P6K$
#    url: jdbc:mysql://localhost:3306/raze?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
