server:
  port: 8105
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
spring:
  datasource:
    password: M!r#P6K$
    url: jdbc:mysql://localhost:3306/raze?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
